### ISSUE TITLE
Richietsa

### ISSUE THREAD

**Issue by Tek74** [fablab-imperia/PesaturaArnie#1]
Ciao sono Nicola, non conosco tanto Arduino ne Github....  pero' sto entrando nel mondo
Ora un po' di programmazione l'ho capita ma volevo chiedere un aiuto, ovvero vorrei anch'io fare un sistema per pesature arnia prendendo spunto da Voi. Volevo pero' usare dei pezzi che ho in casa, ovvero arduino uno e su questo mettere la seguente scheda Ttgo t-call v1.3 esp32 (che costa poco) e mettere anche sensore temperatura e umidita' AM2301...
E' fattibile applicare la scheda gsm ttgo su arduino uno? nel caso mi daresti qualche aiuto sulle librerie e programmazione?

Ringrazio e scusa il disturbo

Ciao
Nicola

**Comment by ssemeria** [comment]
Ciao Nicola.
Il codice è stato scritto per Arduino MKR, quindi tutta la parte di invio dei dati deve essere modificata usando una libreria con cui la scheda che suggerisci è compatibile (ad esempio https://github.com/vshymanskyy/TinyGSM ). La Ttgo t-call è interessante (avremmo sicuramente usato quella, se lo avessimo saputo). Sarebbe interessante creare una nuova versione del progetto basata sulla scheda che suggerisci in questo momento non siamo però in grado di seguirne gli sviluppi. Ti aggiorniamo in caso avviassimo un progetto nuovo, per il momento puoi pensare di forkare il nostro repository e creare un tuo progetto se vuoi.

**Comment by Tek74** [comment]
Grazie veramente... sono neofita dunque necessito di parecchie istruzioni sia su arduino che sull'uso di github.... comunque sto prendendo spunto dai vostri file e per adesso sono riuscito a far leggere il sensore temperatura e umidità Am2301 con la scheda TTGO,  sto collegando anche hx711 e devo testare lo sketch che per ora non mi da errori
Poi dovrò unirli ... è se non sei esperto come me fai veramente fatica.... capisco anche che però sono partito con un progetto un po complesso ma pian piano si fa dai.... mai mollare

Ciao
Nicola
