### ISSUE TITLE
Arnia Tek Pesatura arnia 2.0

### ISSUE THREAD

**Issue by Tek74** [fablab-imperia/PesaturaArnie#2]
Pesatura Arnie

Scopo di questo progetto è la realizzazione di un semplice sistema per la pesatura e il monitoraggio di Arnie. Il sistema controlla il peso di un'arnia mediante bilancia a celle di carico, umidità e temperatura e consente un monitoraggio continuo appoggiandosi ad una piattaforma Web e avvisa mediante notifica in caso di anomalia (peso troppo basso, batteria al minimo). Viene usata una nuova scheda TTGO t-call v1.4 e ulteriore sensore di temperatura tipo AM2301.

**Comment by federicobriata** [comment]
ciao @Tek74 , vedo che segui il nostro fork di hiveeyes
https://github.com/federicobriata/Bilancia-per-alveari
che praticamente fa quello che ti serve.. che idea avevi in mente per Arnia Tek?

**Comment by ssemeria** [comment]
Chiedo scusa, ma questo non è un forum di discussione. Se non avete segnalazioni relative a questo repository Github, vi chiedo la cortesia di continuare la conversazione tra di voi utilizzando altri canali più appropriati.

**Comment by Tek74** [comment]
Si scusa ssemeria non conosco github...non capisco come si usa... se riuscite cancellate pure la mia parte... Grazie

**Comment by ssemeria** [comment]
Nessun problema. L'idea è che scrivi qui se vuoi segnalare problemi nel codice del nostro progetto su cui vuoi lavorare o vuoi che noi lavoriamo. Questo progetto è un hobby quindi ci dedichiamo davvero poco tempo.

**Comment by federicobriata** [comment]
@ssemeria pure per me questo è un hobby e per aiutare alcuni amici nel Acquese e Genovese, io manco ho più le arnie da quando è mancato mio nonno..
Ad ogni modo per quello che ne sapevo voi del fablab e tek74 potevate anche conoscervi e questo ticket poteva sembrare una richiesta di nuova features e la mia una offerta di collaborazione, fino ai tuo commento non mi sentivo OT o fuori posto visto che il tema mi pare pressappoco lo stesso. 
Se hai anche un link su forum dove poter continuare questa discussione ben venga, io non ne conosco. Grazie

@Tek74 la mia email la trovi sulle commit del mio progetto, il resto su Google. ti lascio anche il telegram: @fedegroovie
Ciao
